version: 0.2

env:
  variables:
    SRC_DIR: src/github.com/gemcook/gc-tech-sls

phases:
  install:
    commands:
      - yarn install --frozen-lockfile --non-interactive
  pre_build:
    commands:
      - export GIT_BRANCH=`git symbolic-ref HEAD --short 2>/dev/null`; if [ "$GIT_BRANCH" == "" ] ; then GIT_BRANCH=`git branch -a --contains HEAD | sed -n 2p | awk '{ printf $1 }'` && export GIT_BRANCH=${GIT_BRANCH#remotes/origin/} ; fi
      - export BRANCH=$GIT_BRANCH

      # 環境情報の表示
      - echo BRANCH $BRANCH
      - echo node \"$(node -v)\"
      - echo yarn \"$(yarn --version)\"
      - echo awscli \"$(aws --version)\"
      - echo sls version \"$(sls version)\"
  build:
    commands:
      - yarn install
      - echo $BRANCH
      # Node build & deploy
      - |
        (
          if [ "${BRANCH}" == "develop" ]; then
            sls deploy --region us-east-1 --stage dev
          elif [ "${BRANCH}" == "release" ]; then
            sls deploy --region us-east-1 --stage stg
          elif [ "${BRANCH}" == "master" ]; then
            sls deploy --region us-east-1 --stage prd
          else
            echo 'skip serverless Node deploy'
          fi
        )
